# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "XVhis+PnvHrfrgmS98za4N/5UO29xwNNUhgMuDSN0IJ3Y8fgrH5wNW6D25TXwnX95L9xbCRP+mzv9/uF9Hl5kN1KY7x57yO93RLqdLExV0XMm9vNM0m6sfpCvhAT81Gh18qNfPge+3e2Bk15qfJgkK9fU7Lstz5R2SgUrkd4/KR1JGy+6nxawysuc6EdyA8am6Lt/hnudKqJPdH9ovquTm3tVJ0WaScIhMUq+IezbZOJYlmhRYa9ZbwNt+9RDqeMS1vnv8DlYIkr6HwGNnRINOYT8Esy8KogWFU0xPXj80vuN4LafXpe48x8+/9HBHTQYkfzm/qT30JLP2T5Esiv3WtXFva87GCrIvnOwE7Y3VfhNqlPw5fYjqHKCsNRV2jYt57uNJ5dkRchtGyDjg8mHZXEK+K2ljsJBoHYh3KAumzILci5qkl1wyyK5N40rJIuWaQi4eGKAH00xIH3Jg78ShCxV6T7B7vzbYhfij8vRoVk37ILBUo72NRYOdZZSgMFcSffmt0kUGNt0S7CSQ9X0SystV/xxCHi3/kfo6YN61MUTgKkHGhWXh1LSpb6uO5n8rJo8HMQ3Hkn3yrCO02KpcqA+BTTQhOqkjFQLlX71YNwBJfm8wW8vpg3Zk1uGqW9461zT5RUT260uIY7PKZeiWUS8MYfLIuLyYslv/2f5GU="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
