travis:
  secure:
    BINSTAR_TOKEN: XVhis+PnvHrfrgmS98za4N/5UO29xwNNUhgMuDSN0IJ3Y8fgrH5wNW6D25TXwnX95L9xbCRP+mzv9/uF9Hl5kN1KY7x57yO93RLqdLExV0XMm9vNM0m6sfpCvhAT81Gh18qNfPge+3e2Bk15qfJgkK9fU7Lstz5R2SgUrkd4/KR1JGy+6nxawysuc6EdyA8am6Lt/hnudKqJPdH9ovquTm3tVJ0WaScIhMUq+IezbZOJYlmhRYa9ZbwNt+9RDqeMS1vnv8DlYIkr6HwGNnRINOYT8Esy8KogWFU0xPXj80vuN4LafXpe48x8+/9HBHTQYkfzm/qT30JLP2T5Esiv3WtXFva87GCrIvnOwE7Y3VfhNqlPw5fYjqHKCsNRV2jYt57uNJ5dkRchtGyDjg8mHZXEK+K2ljsJBoHYh3KAumzILci5qkl1wyyK5N40rJIuWaQi4eGKAH00xIH3Jg78ShCxV6T7B7vzbYhfij8vRoVk37ILBUo72NRYOdZZSgMFcSffmt0kUGNt0S7CSQ9X0SystV/xxCHi3/kfo6YN61MUTgKkHGhWXh1LSpb6uO5n8rJo8HMQ3Hkn3yrCO02KpcqA+BTTQhOqkjFQLlX71YNwBJfm8wW8vpg3Zk1uGqW9461zT5RUT260uIY7PKZeiWUS8MYfLIuLyYslv/2f5GU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
