travis:
  secure:
    BINSTAR_TOKEN: 4RX+g1qjUegWjAK0+D5ChbeDXYHg46XXbuVk4vPa5jg3A8kkrXiuO5Q1MOj35WQxL3GHzcf+cb6SHQfBtBMH1cGYMWYPNklW19e4+INUCIy5rc9bpVgvM4QCktWoSrrqqDD/0EIDaF6+mj+5Hupm0NSoLQH48L6qVdXXT66cN9EX4pqfFGE/Vz+26IjDkFTQe3p+j4IM2+ilwlAyrnAJoamBhG4UseoX5PN4t/eQzxEwH/8QCM22DR5MJqrA8tmE/+VRqW8xItawcXXPHpPen/lFg905YrB1TBJYQGOm3eFlwSE873/QHEzXREXLMyUwq1hF1O1ykB+t7Cgqcpidf2xDN9Nov9MurPlB3YWF08RcBV5mcYDVafenhEolO3YqExaCBSBjgCAxAe/lQDBKsgWLz36MgkoMuSasnjYXvtcjMcIbdjrX83KOhveQ7POH7FrQHioaNJk8Klc8skMVrBp7i7M98PMjbb6ch491VD0NutcthfgwwgDurWKvH1ej0M6iG31R9VbmgRuA+3yZqVrf0olDLyNyzdzfNrMObJvBFI3zJp7UVCsFMkVRa1WJ/quu+kVvNcOACj21jmIBTOp3zucsv+7PvVg3+YkmVx0b/xVYImLTLeEJ5qjHQPqaCMDTAPtyJYFmm2mUvoQilT1/Rg0nROh+ZocVOeuHD8Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
