travis:
  secure:
    BINSTAR_TOKEN: DCazayDQkCTOg+AbVPsaS367ti3/PK31Ub4igOD+IzjQOoGeYUPJE632iD1YkpRDFH2UYx6KyF+3G9A9K9c+rmFnjGg40out9GIDtbJ2KnyM+e8uCM90wRS1ScAF/HmVF6DQtWasO8haO2SP+k+Ly7EFTgRrtihFkMJM7b+fm8/YdEfn6cVBgQsJ9BRbmrFO/36P2SO0B4S5dDh0SrKcbNg3WwPXiDsobXf5w9qHsDj5d4N8Hy0skLGhaSMwiyIqjgkpVfFLGNPoGVTXJ/bFSgAD9LByCxaom5YeStO9KYrF0iINE8AuPsPSQsSpt6l6HLGPJW+oW4H1CowYWEiIPQ+ZBGtUPXcVghFYTv7ny3NHVFTtskGme2dhLOUZCJRqKoGQA8jQWH/UBVAaXv1jjrPqP7+cvdQP9TKWHC52/1HYxOYajBDbvQVm4Nhds83xFMrVVBjz8ZBCfUlHv0yd+9mvUdDp81hRevsguLZ2/G29ekOiDE7YFXnH8JNwTPXwnOvtp+dXkiDcV4Udl1uX4k1wiU1emj6U+irLKcEC7HeoRQ8DcqF4HaAT4tVG1eud+FVsH10CIbcVMpj/OTQS//PKqPJvXNzFGWQQpMWxAoYsunOCQBtxKdliGcJnRETzyX6ZzBGoR28lfNQVUVcY6+RoLqZp8gIaFd5xra9fgjM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
