travis:
  secure:
    BINSTAR_TOKEN: oqcQTX1l3ZIun/xcMk5AUkbtUO2SCD+jMBlVHzK7PBh0OoTUOUR4ElINHkKkFpxgn9yT9EldhDXK94oGr+hJ4Z3+vPVVCv8IivNRqDgxY8yxWplZLtc+FDDZZ75HmfwzLCYIPV+a1HoDxSjrVBgIg0muaWjVEclQv/+ioWpx/UL/pgG4O2JliTbXKy2zMmlEoNqzXSnloBHsuoPogQyBGJb8KAjfuXkBq1Jo717tmmrOo/o4Tn4V7rvkwpHSbUYAS6BXD6ioba5/OLlh4vzaZgJ12Asl8bXDe2gxpTT+orowiJHGZr+Hv5ZIU8KjH46Sc1ZiNsJgKg8Tf4jbjj6wrs0hy6ay2K856oV6lZKr0UbQA8QiGsBZHrlYaWA1jg7LK4eummDK0JtWMGvSKKjzkYeqsKyVeL2K2ru9zhklgCH3irzT2oJ7aM5QhtDjSdJ4oGmHLUlxrA0qDJOY7JAA5K7BJ+8wwRV7z/aoxPqOHIWTwTUtTqul0eIyb/+wM0oE3wRh7G7HYiwwBE9dEUNaru4hWJlVBMOhwleH4bLUEp9Z+f4VknsE50ahdYXKIMo8HrwGWA9BppnB249Gqxyc7hC6EEaIzm09pPtC+vakl6Cep3h1kiawj+arCgyz7iX6gUrlm+Ez2MILUrg5B8EfBxRnpKvMrquphODRJ4w+uD0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
